services:
  - type: web
    name: ats-resume-analyzer-api
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: CORS_ORIGINS
        sync: false
      - key: EMBEDDING_MODEL_NAME
        value: all-MiniLM-L6-v2
      - key: OPENAI_API_KEY
        sync: false
      - key: OPENAI_MODEL
        value: gpt-4.1-mini
